packages:
  - "packages/*"
  - "packages/@wterm/*"
  - "packages/@internal/*"
  - "apps/*"
  - "examples/*"
  - "e2e/harness"

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - "@vercel/geistdocs@1.28.1"

allowBuilds:
  "@mongodb-js/zstd": false
  "cpu-features": false
  "esbuild": false
  "msw": false
  "node-pty": true
  "node-liblzma": false
  "sharp": false
  "ssh2": false
  "unrs-resolver": false
